config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [ :index, :show, :edit, :update ] do
    resources :tickets, only: [ :index ]
  end



  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # get '/users/:id/edit', to: 'users#edit'
  # patch '/users/:id/', to: 'users#update'

  resources :user_skills, only: [ :new, :create, :destroy ]

  resources :timeslots, only: [ :new, :create, :destroy ] do
    resources :tickets, only: [ :new, :create ]
  end

  resources :tickets, only: :destroy

  resources :tickets, only: [] do
    resources :reviews, only: [ :new, :create ]
  end

  root to: 'pages#home'
  get "/components", to: 'pages#components'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  has_many :user_skills, dependent: :destroy
  has_many :timeslots, dependent: :destroy
  has_many :skills, through: :user_skills
  has_many :tickets, through: :timeslots
  has_many :booked_tickets, class_name: 'Ticket', foreign_key: 'user_id', dependent: :destroy
  has_many :reviews, through: :tickets
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :bio, length: { maximum: 500 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def index  
    @users = User.all
    authorize @users
    
    parse_date_range
    filtered_timeslots = Timeslot.where('start_time BETWEEN ? AND ?', @dates.first, @dates.last)
    
    available_filtered_timeslots = filtered_timeslots.reject do |timeslot|
      timeslot.ticket
    end
    @filtered_teachers = available_filtered_timeslots.map do |timeslot|
      timeslot.user
    end.uniq
  end

  def show
    mark_map
    @user_skills = @user.user_skills.includes(:skill)
    @reviews = @user.reviews
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to @user, notice: 'Your update was successfull!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def mark_map
    find_user
    if @user.latitude && @user.longitude
      @mark = {
        lgn: @user.longitude,
        lat: @user.latitude
      }
    end
  end

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :photo, :city)
  end

  def parse_date_range
    @dates = params[:beginning].to_s.split('to')
    @dates.map { |date| DateTime.parse(date) }
  end
end

app/views/users/edit.html.erb
<div class="form-container container">
  <h2>Edit Profile</h2>

  <%= simple_form_for(current_user, url: user_path(current_user), method: 'patch') do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "first name" }%>
      <%= f.input :last_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :photo, as: :file %>
      <%= f.input :bio,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "bio" }%>
      <%= f.input :city,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "city" }%>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Edit", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to 'Back', user_path(current_user), class: 'btn btn-primary' %>

</div>

app/views/users/index.html.erb
<div class="card-bg-white my-3">

  <div class="container card-bg-white my-5">
    <div class="form-wrapper" style="width: 250px; margin: 50px auto;">
      <h4 class="mb-3">Filter by time period</h4>

      <%= simple_form_for :search, method: "get" do |f| %>
        <%= f.input :beginning, as: :string, input_html: {id: "range_start", name: 'beginning' } %>
        <%= f.input :end, as: :string, input_html: {id: "range_end",  name: 'end' } %>
        <%= submit_tag ("Filter"), class: "btn btn-filter mt-2 w-100" %>
      <% end %>
    </div>
  </div>

  <hr>

  <% if @filtered_teachers.empty? %>
    <% @teachers = @users %>
    <div class="teacher-browse-title card-bg-white name-bold mt-4 mb-3"><h2>Teachers</h2></div>
  <% else %>
    <% @teachers = @filtered_teachers %>
    <div class="teacher-browse-title card-bg-white name-bold mt-4 mb-3"><h2>Teachers</h2></div>
  <% end %>

  <div class="cards-container d-flex flex-wrap w-100 card-bg-white">
    <% @teachers.reject { |user| user.timeslots.empty? }.each do |user| %>
      <div class="card-teacher-index d-flex my-3 mx-2">
        <div class="color-box">
          <h1><%= user.first_name %> <%= user.last_name %></h1>

          <div class="teacher-info">
            <% if user.bio.present? %>
              <% if user.bio.length > 120 %>
                <p><%= user.bio[0..120] %>...</p>
              <% else %>
                <p><%= user.bio %></p>
              <% end %>
            <% end %>
          </div>

          <%= link_to (user_path(user)), target: "_blank" do %>
            <% if user.photo.attached? %>
              <div><%= cl_image_tag user.photo.key, crop: :fill, class: "avatar-teacher" %></div>
            <% else %>
              <div><%= image_tag "https://instastatistics.com/images/default_avatar.jpg", class: "avatar-teacher" %></div>
            <% end %>
          <% end %>

          <div class="learn-btn"><%= link_to 'learn more', user_path(user), target: "_blank" %></div>
        </div>

        <div class="teacher-skills">
          <% user.skills.each do |skill| %>
            <div class="skill-tag"><%= skill.name %></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 py-3 card w-50 profile-card">

  <% if @user.photo.attached? %>
    <%= cl_image_tag @user.photo.key, crop: :fill, class: "avatar-lg-round my-1 mt-4 card-img-top" %>
  <% else %>
    <%= image_tag "https://instastatistics.com/images/default_avatar.jpg", class: "avatar-lg-round my-1 mt-4 card-img-top" %>
  <% end %>

  <div class="my-4 edit-buttons">
    <% if policy(@user).edit? %>
      <%= link_to 'Edit profile', edit_user_path, class: 'btn-edit mr-2' %>
      <%= link_to 'Edit settings', edit_user_registration_path, class: 'btn-edit' %>
    <% end %>
  </div>

  <h2 class="profile-name"><%= @user.first_name %> <%= @user.last_name %></h2>

  <div class="profile-skills-container">
    <ul class="list-skills">
      <% @user_skills.each do |user_skill| %>
        <li class="profile-btn-skill">
          <%= user_skill.skill.name %>

          <% if policy(@user).destroy? %>
              <span class="badge badge-light ml-1"> <%= link_to 'X', user_skill_path(user_skill), method: 'delete'%> </span>
          <% end %>
        </li>
      <% end %>

      <% if policy(@user).edit? %>
        <li class="skill-add-btn">
          <%= link_to '+', new_user_skill_path, class: 'skill-add-btn' %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="profile-bio">
    <% if @user.bio.present? %>
      <p><%= @user.bio %></p>
      <p class="profile-email"><%= @user.email %></p>
    <% end %>
  </div>

  <div class="card-user-timeslots mt-3">
    <div class="profile-timeslot-title">
      <h3 class="mr-2">Timeslots</h3>
      <% if policy(@user).edit? %>
         <%= link_to 'Add a timeslot', new_timeslot_path, class: 'btn-add-timeslots' %>
      <% end %>
    </div>

    <div class="profile-timeslots-container">
      <% if @user.timeslots.present? %>

        <div class="list-timeslots">
          <% @user.timeslots.order(start_time: :asc).each do |timeslot| %>

            <% if timeslot.start_time > Time.now %>

              <div class="timeslot-element">
                <% if timeslot.ticket %>
                  <p class="closed-timeslot">
                    <%= timeslot.start_time.strftime("%A, %d %B %Y, %H:%M") %>
                  </p>
                <% else %>
                  <p class="open-timeslot">
                    <%= timeslot.start_time.strftime("%A, %d %B %Y, %H:%M") %>
                  </p>
                <% end %>

                <% if policy(@user).destroy? %>
                  <%= link_to icon('fas', 'trash-alt'), timeslot_path(timeslot), method: :delete %>
                <% end %>

                <% unless timeslot.ticket%>
                  <% if current_user != @user %>
                    <%= link_to 'Book this slot', new_timeslot_ticket_path(timeslot), class: 'btn-book' %>
                  <% end %>
                <% end %>
              </div>

            <% end %>

          <% end %>
        </div>

      <% else %>
        <p>Oops, looks like you don't have any timeslots yet.</p>
      <% end %>

    </div>

    <% if @user.city %>
      <div id="map"
      style="width: 100%; height: 600px;"
      data-marker="<%= @mark.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    <% end %>
  </div>

  <% if @user.reviews %>
    <div class="reviews">
      <ul>
        <% @user.reviews.each do |review| %>
          <li>
            <%= review.content %>
            <%= review.rating %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>