config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [ :index, :show, :edit, :update ] do
    resources :tickets, only: [ :index ]
  end



  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # get '/users/:id/edit', to: 'users#edit'
  # patch '/users/:id/', to: 'users#update'

  resources :user_skills, only: [ :new, :create, :destroy ]

  resources :timeslots, only: [ :new, :create, :destroy ] do
    resources :tickets, only: [ :new, :create ]
  end

  resources :tickets, only: :destroy

  resources :tickets, only: [] do
    resources :reviews, only: [ :new, :create ]
  end

  root to: 'pages#home'
  get "/components", to: 'pages#components'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
      <a href="https://github.com/juliaf1/opentickets" target="_"><%= icon('fab', 'github') %></a>
      <a href="#" target="_"><%= icon('fas', 'heart') %></a>
      <a href="#" target="_"><%= icon('fas', 'envelope') %></a>
  </div>
  <div class="footer-copyright">
    <p>Made with Rails during Le Wagon Batch 499</p>
  </div>
</div>

<!--

<div class="footer">
  <div class="footer-links">

  </div>

  <div>
    <p>Made with Rails during Le Wagon Batch 499</p>
  </div>
</div>



<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/juliaf1/opentickets"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>
 -->

app/views/shared/_navbar.html.erb
<div class="banner">
  <div class="container">

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Browse Teachers", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "My tickets", user_tickets_path(current_user), class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Browse Teachers", users_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Browse Teachers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My tickets", user_tickets_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Browse Teachers", users_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
>>>>>>> master
  </div>
</div>