config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [ :index, :show, :edit, :update ] do
    resources :tickets, only: [ :index ]
  end



  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # get '/users/:id/edit', to: 'users#edit'
  # patch '/users/:id/', to: 'users#update'

  resources :user_skills, only: [ :new, :create, :destroy ]

  resources :timeslots, only: [ :new, :create, :destroy ] do
    resources :tickets, only: [ :new, :create ]
  end

  resources :tickets, only: :destroy

  resources :tickets, only: [] do
    resources :reviews, only: [ :new, :create ]
  end

  root to: 'pages#home'
  get "/components", to: 'pages#components'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :timeslot
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :timeslot_id, uniqueness: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_teacher, only: [:create]
  before_action :find_timeslot, only: [:new, :create]

  def index
    @student_tickets = Ticket.where(user_id: params[:user_id])
    @teacher_tickets = Ticket.joins(:timeslot).where(timeslots: { user_id: params[:user_id] })
  end

  def new
    @ticket = Ticket.new
    authorize @ticket
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.timeslot = @timeslot
    authorize @ticket
    respond_to do |format|
      if @ticket.save
        TicketMailer.with(ticket: @ticket).new_ticket_email.deliver_later
        format.html { redirect_to user_tickets_path(current_user), notice: 'Your ticket was created successfully' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { redirect_to user_path(@timeslot.user_id) }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    authorize @ticket
    if @ticket.timeslot.start_time - Time.now > 86_400
      @ticket.destroy
      redirect_to user_tickets_path(current_user), notice: 'Your ticket was canceled 😞'
    else
      redirect_to user_tickets_path(current_user), alert: "You can't cancel a Ticket with less than 24h notice!"
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:description)
  end

  def find_timeslot
    @timeslot = Timeslot.find(params[:timeslot_id])
  end

  def find_teacher
    find_timeslot
    @teacher = @timeslot.user
  end
end

app/views/tickets/index.html.erb
<div class="container tickets-container text-center border px-2">

    <% unless @student_tickets.first.nil? %>
      <div class="card-title px-2">
        <h2 class="name-bold">Tickets as a student</h2>
      </div>

      <div class="d-flex flex-wrap text-center justify-content-around">
        <% @student_tickets.each do |ticket| %>
          <div class="teacher-card my-2 mx-1 border">

            <div class="student-card-color-background">
               <%= link_to 'cancel ticket', ticket_path(ticket),
                  method: :delete, data: {confirm: 'Are you sure you want to cancel this ticket?'},
                  class: 'btn btn-dark btn-sm cancel-btn mt-4' %>
              <div class="card-img">
                <%= link_to (user_path(ticket.timeslot.user)) do %>
                  <% if ticket.timeslot.user.photo.attached? %>
                    <%= cl_image_tag ticket.timeslot.user.photo.key, crop: :fill, class: "avatar-large my-1 card-img-top" %>
                  <% else %>
                    <%= image_tag "https://instastatistics.com/images/default_avatar.jpg", class: "avatar-large my-1 card-img-top" %>
                  <% end %>
                <% end %>
              </div>
            </div>

            <p class="name-bold"> <%= ticket.timeslot.user.first_name %> </p>

            <div class="card-description-student ">
              <p> <%= ticket.description %></p>
              <p class="name-bold"> <%= ticket.timeslot.start_time.strftime("%A, %d %B %Y")%></p>
              <p class="card-ticket-time name-bold"> <%= ticket.timeslot.start_time.strftime("%H:%M")%></p>
              <% unless ticket.review %>
                <%= link_to 'add review', new_ticket_review_path(ticket), class: 'btn btn-sm btn-secondary review-btn' %>
              <% end %>
            </div>

          </div>
        <% end %>
      </div>

    <% else %>
      <div class="card-title mb-5 px-2">
        <h2 class="name-bold">Tickets as a student</h2>
        <p>Oops, you don't have any tickets booked.</p>
        <%= link_to 'Browse our teachers to book a ticket', users_path %>
      </div>
    <% end %>

    <hr>

    <% unless @teacher_tickets.first.nil? %>
      <div class="card-title px-2">
        <h2 class="name-bold p-3">Tickets as a teacher</h2>
      </div>

      <div class="d-flex flex-wrap text-center justify-content-around">
        <% @teacher_tickets.each do |ticket| %>
          <div class="teacher-card my-2 mx-1 border">

            <div class="teacher-card-color-background">
              <%= link_to 'cancel ticket', ticket_path(ticket),
                method: :delete, data: {confirm: 'Are you sure you want to cancel this ticket?'},
                class: 'btn btn-dark btn-sm cancel-btn mt-4' %>
              <div class="card-img">
                <%= link_to (user_path(ticket.user)) do %>
                  <% if ticket.user.photo.attached? %>
                    <%= cl_image_tag ticket.user.photo.key, crop: :fill, class: "avatar-large my-1 card-img-top" %>
                  <% else %>
                    <%= image_tag "https://instastatistics.com/images/default_avatar.jpg", class: "avatar-square my-1 card-img-top" %>
                  <% end %>
                <% end %>
              </div>
            </div>

            <p class="name-bold"> <%= ticket.user.first_name %> </p>

            <div class="card-description">
              <p> <%= ticket.description %></p>
              <p class="name-bold"> <%= ticket.timeslot.start_time.strftime("%A, %d %B %Y")%></p>
              <p class="card-ticket-time name-bold"> <%= ticket.timeslot.start_time.strftime("%H:%M")%></p>
            </div>

          </div>
        <% end %>
      </div>

    <% else %>
      <div class="card-title mt-5 px-2">
        <h2 class="name-bold">Tickets as a Teacher</h2>
        <p>Looks like you're not teaching anyone yet.</p>
        <%= link_to 'Add your available timeslots so people can book you', new_timeslot_path %>
      </div>
    <% end %>

</div>

app/views/tickets/new.html.erb
<div class="container text-center my-5">
  <div class="row">
    <div class="col-sm">
      <h1>Book your ticket with <%= @timeslot.user.first_name %></h1>
      <p class="mb-5">Write a brief description of your problem or what you would like to learn</p>
      <%= simple_form_for @ticket, url: timeslot_tickets_path(@timeslot), method: 'post' do |f| %>

        <%= f.input :description, label: false %>

        <%= f.button :submit, 'Create Ticket', class: 'btn-skill' %>
      <% end %>
    </div>
  </div>
</div>

<div style="height: 500px"></div>