config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users, only: [ :index, :show, :edit, :update ] do
    resources :tickets, only: [ :index ]
  end



  # get '/users', to: 'users#index'
  # get '/users/:id', to: 'users#show'
  # get '/users/:id/edit', to: 'users#edit'
  # patch '/users/:id/', to: 'users#update'

  resources :user_skills, only: [ :new, :create, :destroy ]

  resources :timeslots, only: [ :new, :create, :destroy ] do
    resources :tickets, only: [ :new, :create ]
  end

  resources :tickets, only: :destroy

  resources :tickets, only: [] do
    resources :reviews, only: [ :new, :create ]
  end

  root to: 'pages#home'
  get "/components", to: 'pages#components'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :user
  has_one :ticket, dependent: :destroy

  validates :start_time, presence: true
  validates :start_time, uniqueness: { scope: :user_id }
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  def new
    @timeslot = Timeslot.new
    authorize current_user
  end

  def create
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.user = current_user
    authorize @timeslot
    respond_to do |format|
      if @timeslot.save
        format.html { redirect_to current_user, notice: 'Timeslot was successfully created' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])
    authorize @timeslot

    @timeslot.destroy
    redirect_to user_path(current_user)
  end

  private

  def timeslot_params
    params.require(:timeslot).permit(:start_time)
  end
end

app/views/timeslots/new.html.erb
<div class="container text-center my-5">
  <div class="row">
    <div class="col-sm">
      <h1>Add a timeslot</h1>
      <p class="mb-5">Pick a time and click save</p>
      <%= simple_form_for @timeslot, url: timeslots_path, method: 'post' do |f| %>

        <%= f.input :start_time, as: :string, input_html: {class: 'datepicker'} %>

        <%= f.button :submit, 'Save', class: 'btn-skill' %>
      <% end %>
    </div>
  </div>
</div>

<div style="height: 500px"></div>